export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as About} from './About'
export {default as LZXVidiot} from './LZXVidiot'
export {default as VideoSynthesizers} from './VideoSynthesizers'